# Generated by Django 3.2.25 on 2024-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_rename_type_question_type_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(verbose_name='question id')),
                ('answer', models.JSONField(verbose_name='answer')),
            ],
        ),
    ]
