# Generated by Django 3.2.25 on 2024-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0149_correctanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='questions_ids',
            field=models.JSONField(blank=True, help_text='A list of question ids for the questionnaire.', null=True, verbose_name='questions ids'),
        ),
    ]
