# Generated by Django 3.2.25 on 2024-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_contest_questions_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100, verbose_name='name user')),
                ('name_question', models.CharField(max_length=100, verbose_name='name question')),
                ('question_id', models.IntegerField(verbose_name='question id')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('answer', models.JSONField(verbose_name='answer')),
                ('correct', models.BooleanField(verbose_name='correct')),
            ],
        ),
    ]
